# Generated by Django 4.0 on 2021-12-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacao_perda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingLocalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('street', models.CharField(max_length=255)),
                ('complement', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('federative_unit', models.CharField(max_length=5)),
            ],
        ),
    ]
