# Generated by Django 4.0 on 2021-12-25 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacao_perda', '0002_farminglocalization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_farming', models.CharField(max_length=100)),
                ('farming_event', models.CharField(choices=[('EXCESSIVE_RAN', 'Chuva Excessiva'), ('FROST', 'Geada'), ('HAILSTORM', 'Granizo'), ('BARREN', 'Seca'), ('WINDSTORM', 'Vendaval'), ('BOLT', 'Raio')], max_length=20)),
                ('date_harvest', models.DateField(auto_now_add=True)),
                ('farming_localization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunicacao_perda.farminglocalization')),
            ],
        ),
    ]
