# Generated by Django 4.0 on 2021-12-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacao_perda', '0003_farming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmingproducer',
            name='cpf_producer',
            field=models.IntegerField(),
        ),
    ]
